### ISSUE TITLE
error in compilation

### ISSUE THREAD

**Issue by iceberg1369** [Erensu/cors#2]
CMake Error at lib/lapack/CMakeLists.txt:343 (add_subdirectory):
  The source directory

    /home/iceberg/cors/lib/lapack/TESTING

  does not contain a CMakeLists.txt file.

**Comment by lzhuance** [comment]
just comment these sentence in the .\CMakeLists.txt and then re-compile.
```
# if(BUILD_TESTING)
#   add_subdirectory(TESTING)
# endif()
```

**Comment by lzhuance** [comment]
> CMake Error at lib/lapack/CMakeLists.txt:343 (add_subdirectory): The source directory
> 
> ```
> /home/iceberg/cors/lib/lapack/TESTING
> ```
> 
> does not contain a CMakeLists.txt file.

**Comment by lzhuance** [comment]
> CMake Error at lib/lapack/CMakeLists.txt:343 (add_subdirectory): The source directory
> 
> ```
> /home/iceberg/cors/lib/lapack/TESTING
> ```
> 
> does not contain a CMakeLists.txt file.

just comment these sentence in the .\CMakeLists.txt and then re-compile.
``
# if(BUILD_TESTING)
#   add_subdirectory(TESTING)
# endif()
``

**Comment by lzhuance** [comment]
> CMake Error at lib/lapack/CMakeLists.txt:343 (add_subdirectory): The source directory
> 
> ```
> /home/iceberg/cors/lib/lapack/TESTING
> ```
> 
> does not contain a CMakeLists.txt file.

just comment these sentence in the .\CMakeLists.txt and then re-compile.
```
# if(BUILD_TESTING)
#   add_subdirectory(TESTING)
# endif()
```
