### ISSUE TITLE
VRS

### ISSUE THREAD

**Issue by jareermohammed** [Erensu/cors#7]
Dear,
Thank you for the CORS software.
I just have a small issue that I dont know if it is I miss something in setting or what.
Attached I have some stations that working perfectly and submitting the observations to my sever, however, VRS stay disconnected! why could be that?
the second question, I have followed the code and found that ntrip caster is already implemented, but I cannot access the caster so the caster showing my CORS stations as well as the VRS.

Thank you in advance, waiting for you reply.
![Screenshot 2023-08-23 202405 - Copy](https://github.com/Erensu/cors/assets/10739892/a88debd7-23e0-4c7a-bb4f-a8dc554f5d65)

**Comment by iceberg1369** [comment]
Hello mohammad
Could you please send me your email address. Im intersted in your work

**Comment by jareermohammed** [comment]
jareermohammed at uowasit.edu.iq

**Comment by iceberg1369** [comment]
@jareermohammed it seems like you have not checked your inbox

**Comment by kroegman** [comment]
Hi guys, you both still on this? any of you got it fully functional?

**Comment by iceberg1369** [comment]
@kroegman the original author barely reply to our requests. is there anything we could help?

**Comment by kroegman** [comment]
I'll send you an email:) thanks for the response!
